GET http://localhost:8000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNzb3AiLCJpYXQiOjE3MjM2MzU2ODQsImV4cCI6MTcyMzYzNTY5OX0.mrv_afD0z85tzE_DuUu0yaNeBq6SoiugscOubp761g4

###

GET http://localhost:4000/token
Content-Type: appplication/json

{
    "token" :  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoidXNzb3AiLCJpYXQiOjE3MjM2MzU1Nzh9.4KZH5Baivem-siHkArBQ5jNWbDhjyGJM85H0SiNVj1I"

}

###

POST http://localhost:4000/login
Content-Type: application/json


{
    "username" : "ussop"
}